In [21]:
import pandas as pd
import numpy as np
import math

### Task 1

In [22]:
df= pd.read_csv("insurance.csv")

In [23]:
df.head(10)

   age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520
5   31  female  25.740         0     no  southeast   3756.62160
6   46  female  33.440         1     no  southeast   8240.58960
7   37  female  27.740         3     no  northwest   7281.50560
8   37    male  29.830         2     no  northeast   6406.41070
9   60  female  25.840         0     no  northwest  28923.13692

In [24]:
df.shape
# 1338 rows and 7 columns
# column labels represent information about an individual
# Label is likely charges
# The rest of the columns minus index and charges

(1338, 7)

### Task 2: Make a Guess

In [25]:
# player1: $10k
# player2: $5k

### Task 3: Compute a Mean Baseline

In [26]:
df["mean_baseline"] = df["charges"].mean()
mean_baseline = df["charges"].mean()
df.head()

   age     sex     bmi  children smoker     region      charges  mean_baseline
0   19  female  27.900         0    yes  southwest  16884.92400   13270.422265
1   18    male  33.770         1     no  southeast   1725.55230   13270.422265
2   28    male  33.000         3     no  southeast   4449.46200   13270.422265
3   33    male  22.705         0     no  northwest  21984.47061   13270.422265
4   32    male  28.880         0     no  northwest   3866.85520   13270.422265

-  Q1: Player1 was almost spot on.
-  Q1: player 2 was double the guess.

-  Q2: No, because ther are some big outliers that bring the mean up.

### Task 4: Compute MAE for Your Baseline

In [27]:
df["charges"].mean()
df["errors"] = abs(df["charges"] - mean_baseline)
baseline_mae = df["errors"].mean()

print(baseline_mae)

9091.12658113703

-  Q1: If MAE is 4,000, what does that mean?
-  A: The averages of all the charges are $4,000 off

### Task 5: Compute MSE and RMSE

In [34]:
 
df["errors_squared"] = df["errors"] * df["errors"]
baseline_mse = df["errors_squared"].mean()
print(baseline_mse)

baseline_rmse = math.sqrt(baseline_mse)
print(baseline_rmse)

146542766.49354792
12105.484975561612

-  $s is the unit used
-  RMSE is preferred when you want to penalize big errors

#### Task 6: Build a Grouped Baseline

In [ ]:
df["smoker_mean"] = df.groupby("smoker")["charges"].transform("mean")
df.head()
smoker_mean = df.groupby("smoker")["charges"].mean()
print(smoker_mean)

grouped_mae =

smoker
no      8434.268298
yes    32050.231832
Name: charges, dtype: float64

In [50]:
df["error_v2"] = df["charges"] - df["smoker_mean"]

df["errors_v2"] = abs(df["charges"] - df["smoker_mean"])
v2_baseline_mae = df["errors_v2"].mean()

print(f" baseline v2: {v2_baseline_mae}")
print(f" baseline v1: {baseline_mae}")

 baseline v2: 5662.08960934306
 baseline v1: 9091.12658113703

-  is grouped mae(v2) lower or higher than baseline (v1): Lower
-  What does this say about specificity: the more specifics entered increases the model's potential to be more accurate

### Task 7: Label and Seaparate Features

In [ ]:
x = df[["age", "sex", "bmi", "children", "smoker", "region"]]
y = df["charges"]

print(x.head(3))
print(y.head(3))

#Split x and y instead of keeping them together because we are trying to predict y (charges) in our model.

   age     sex    bmi  children smoker     region
0   19  female  27.90         0    yes  southwest
1   18    male  33.77         1     no  southeast
2   28    male  33.00         3     no  southeast
0    16884.9240
1     1725.5523
2     4449.4620
Name: charges, dtype: float64

### Task 8: Simulate a Train/Test Split

In [55]:
y.shape

(1338,)

In [ ]:
split=round(len(y) * .8)

y_train = y.head(split)
x_train = x.head(split)

y_test = y.tail(len(y)-split)
x_test = x.tail(len(x)-split)

print(len(y_train))  
print(len(y_test))
print(len(x_train))
print(len(x_test))

1070
268
1070
268

-  1.Why is it a problem to test a model on the same data it trained on? 
-  A: It will learn the data and may not predict the way we want it to.

-  2.What is this problem called?
-  A:Overfitting

### Task 9: Evaluate on Test Data Only

In [ ]:
y_train.mean()

y_train.mean() - y_test.mean()



df["charges"].mean()
df["errors"] = abs(df["charges"] - mean_baseline)
baseline_mae = df["errors"].mean()

print(baseline_mae)